version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.19.7
    ports:
      - "8080:8080"
    environment:
      - QUERY_DEFAULTS_LIMIT=20
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-none
    volumes:
      - "./weaviate_data:/var/lib/weaviate"
